services:
  mysql:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
      - ./db-data:/var/lib/mysql
    ports:
      - 3336:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8880:8080

  qooldown:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8881:8881"
